export const APPOINTMENT_CREATE_REQUEST = 'APPOINTMENT_CREATE_REQUEST';
export const APPOINTMENT_CREATE_SUCCESS = 'APPOINTMENT_CREATE_SUCCESS';
export const APPOINTMENT_CREATE_FAIL = 'APPOINTMENT_CREATE_FAIL';

export const APPOINTMENT_OF_PATIENT_LIST_REQUEST =
  'APPOINTMENT_OF_PATIENT_LIST_REQUEST';
export const APPOINTMENT_OF_PATIENT_LIST_SUCCESS =
  'APPOINTMENT_OF_PATIENT_LIST_SUCCESS';
export const APPOINTMENT_OF_PATIENT_LIST_FAIL =
  'APPOINTMENT_OF_PATIENT_LIST_FAIL';
export const APPOINTMENT_OF_PATIENT_LIST_RESET =
  'APPOINTMENT_OF_PATIENT_LIST_RESET';

export const APPOINTMENT_OF_DOCTOR_LIST_REQUEST =
  'APPOINTMENT_OF_DOCTOR_LIST_REQUEST';
export const APPOINTMENT_OF_DOCTOR_LIST_SUCCESS =
  'APPOINTMENT_OF_DOCTOR_LIST_SUCCESS';
export const APPOINTMENT_OF_DOCTOR_LIST_FAIL =
  'APPOINTMENT_OF_DOCTOR_LIST_FAIL';
export const APPOINTMENT_OF_DOCTOR_LIST_RESET =
  'APPOINTMENT_OF_DOCTOR_LIST_RESET';

export const APPOINTMENT_DETAILS_REQUEST = 'APPOINTMENT_DETAILS_REQUEST';
export const APPOINTMENT_DETAILS_SUCCESS = 'APPOINTMENT_DETAILS_SUCCESS';
export const APPOINTMENT_DETAILS_FAIL = 'APPOINTMENT_DETAILS_FAIL';

export const PRESCRIPTION_CREATE_REQUEST = 'PRESCRIPTION_CREATE_REQUEST';
export const PRESCRIPTION_CREATE_SUCCESS = 'PRESCRIPTION_CREATE_SUCCESS';
export const PRESCRIPTION_CREATE_FAIL = 'PRESCRIPTION_CREATE_FAIL';

export const PRESCRIPTION_DETAILS_REQUEST = 'PRESCRIPTION_DETAILS_REQUEST';
export const PRESCRIPTION_DETAILS_SUCCESS = 'PRESCRIPTION_DETAILS_SUCCESS';
export const PRESCRIPTION_DETAILS_FAIL = 'PRESCRIPTION_DETAILS_FAIL';

export const APPOINTMENT_COMPLETED_REQUEST = 'APPOINTMENT_COMPLETED_REQUEST';
export const APPOINTMENT_COMPLETED_SUCCESS = 'APPOINTMENT_COMPLETED_SUCCESS';
export const APPOINTMENT_COMPLETED_FAIL = 'APPOINTMENT_COMPLETED_FAIL';
export const APPOINTMENT_COMPLETED_RESET = 'APPOINTMENT_COMPLETED_RESET';

export const APPOINTMENT_UPDATE_REQUEST = 'APPOINTMENT_UPDATE_REQUEST';
export const APPOINTMENT_UPDATE_SUCCESS = 'APPOINTMENT_UPDATE_SUCCESS';
export const APPOINTMENT_UPDATE_FAIL = 'APPOINTMENT_UPDATE_FAIL';
export const APPOINTMENT_UPDATE_RESET = 'APPOINTMENT_UPDATE_RESET';
