export const PATIENT_REGISTER_REQUEST = 'PATIENT_REGISTER_REQUEST';
export const PATIENT_REGISTER_SUCCESS = 'PATIENT_REGISTER_SUCCESS';
export const PATIENT_REGISTER_FAIL = 'PATIENT_REGISTER_FAIL';

export const PATIENT_LOGIN_REQUEST = 'PATIENT_LOGIN_REQUEST';
export const PATIENT_LOGIN_SUCCESS = 'PATIENT_LOGIN_SUCCESS';
export const PATIENT_LOGIN_FAIL = 'PATIENT_LOGIN_FAIL';
export const PATIENT_LOGOUT = 'PATIENT_LOGOUT';

export const PATIENT_DETAILS_REQUEST = 'PATIENTS_DETAILS_REQUEST';
export const PATIENT_DETAILS_SUCCESS = 'PATIENTS_DETAILS_SUCCESS';
export const PATIENT_DETAILS_FAIL = 'PATIENTS_DETAILS_FAIL';

export const PATIENT_UPDATE_REQUEST = 'PATIENT_UPDATE_REQUEST';
export const PATIENT_UPDATE_SUCCESS = 'PATIENT_UPDATE_SUCCESS';
export const PATIENT_UPDATE_FAIL = 'PATIENT_UPDATE_FAIL';
export const PATIENT_UPDATE_RESET = 'PATIENT_UPDATE_RESET';
