export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const PATIENT_LIST_REQUEST = 'PATIENT_LIST_REQUEST';
export const PATIENT_LIST_SUCCESS = 'PATIENT_LIST_SUCCESS';
export const PATIENT_LIST_FAIL = 'PATIENT_LIST_FAIL';
export const PATIENT_LIST_RESET = 'PATIENT_LIST_RESET';

export const DOCTOR_LIST_REQUEST = 'DOCTOR_LIST_REQUEST';
export const DOCTOR_LIST_SUCCESS = 'DOCTOR_LIST_SUCCESS';
export const DOCTOR_LIST_FAIL = 'DOCTOR_LIST_FAIL';
export const DOCTOR_LIST_RESET = 'DOCTOR_LIST_RESET';

export const APPOINTMENT_LIST_REQUEST = 'APPOINTMENT_LIST_REQUEST';
export const APPOINTMENT_LIST_SUCCESS = 'APPOINTMENT_LIST_SUCCESS';
export const APPOINTMENT_LIST_FAIL = 'APPOINTMENT_LIST_FAIL';
export const APPOINTMENT_LIST_RESET = 'APPOINTMENT_LIST_RESET';

export const PATIENT_DELETE_REQUEST = 'PATIENT_DELETE_REQUEST';
export const PATIENT_DELETE_SUCCESS = 'PATIENT_DELETE_SUCCESS';
export const PATIENT_DELETE_FAIL = 'PATIENT_DELETE_FAIL';

export const DOCTOR_DELETE_REQUEST = 'DOCTOR_DELETE_REQUEST';
export const DOCTOR_DELETE_SUCCESS = 'DOCTOR_DELETE_SUCCESS';
export const DOCTOR_DELETE_FAIL = 'DOCTOR_DELETE_FAIL';

export const APPOINTMENT_DELETE_REQUEST = 'APPOINTMENT_DELETE_REQUEST';
export const APPOINTMENT_DELETE_SUCCESS = 'APPOINTMENT_DELETE_SUCCESS';
export const APPOINTMENT_DELETE_FAIL = 'APPOINTMENT_DELETE_FAIL';
